### ISSUE TITLE
Cannot login in local

### ISSUE THREAD

**Issue by luc-hn** [creativetimofficial/ct-nuxt-argon-dashboard-pro-laravel#1]
Hi team,
I have just set up Nuxt frontend and Laravel API then I try to login in local but always receive 500 Internal Server Error
![image](https://user-images.githubusercontent.com/21037032/109411125-56b92780-79d2-11eb-99c3-52cf5501d5c2.png)

**Comment by luc-hn** [comment]
![image](https://user-images.githubusercontent.com/21037032/109420590-ed530c00-7a05-11eb-8262-4d2154ca59a2.png)
I try to remove project then install again, now the login API just pending and pending

**Comment by teamupdivision** [comment]
Hi @luc-hn,

Thank you for using Creative Tim products. 

Could you please check and make sure the following steps have been folllowed: https://nuxt-argon-dashboard-pro-laravel.creative-tim.com/documentation/examples/api-instalation.html#introduction

Also, please double check if the login details are following the following format: @jsonapi.com.

Let us know if this helped or if you have any other questions.

Best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi there @luc-hn, 

We would like to check if the issue was solved and if there is anything else we can help with. 
Please let us know if you have any other issues. 

Best,
Updivision Team

**Comment by teamupdivision** [comment]
Hi @luc-hn,
 
Hope this solved the problem. We will go ahead and close this ticket. If there is anything else that can be fixed or we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
