### ISSUE TITLE
Can’t update Profile 

### ISSUE THREAD

**Issue by asimag** [creativetimofficial/ct-nuxt-argon-dashboard-pro-laravel#2]
# Prerequisites
Our company Curotec purchased the theme

Please answer the following questions for yourself before submitting an issue.

- [ yes] I am running the latest version
- [ yes] I checked the documentation and found no answer
- [yes ] I checked to make sure that this issue has not already been filed
- [ yes] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected  Behavior 
I should be able to upload picture and update my email etc. 

# Current Behavior

When I update user profile it doesn’t update. I am having a internal server error 500. I can update tags and categories 

What is the current behavior?

# Failure Information (for bugs)
Api call to ‘me’ route throws an internal server error. 

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce
Edit profile and try to submit. It will not submit. 

Please provide detailed steps for reproducing the issue.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MacBook Pro
* Using BigSur and Laravel Valet
* Chrome Browser  latest version 
* 

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by teamupdivision** [comment]
Hi @asimag,

Thank you for reporting this issue and for using Creative Tim products.
 
Could you please send to us a few screenshots or video recording with the steps followed? It will help a lot in investigating this further.
 
All the best,
UPDIVISION Team

**Comment by asimag** [comment]
I have fixed it my self by replacing line 88 in MeController.php with 
-       return Error::create($error);
+      return  new Error(1, $error['status'], null, $error['title'], $error['detail'], $error['source'], null,

**Comment by teamupdivision** [comment]
Hi there @asimag,

Thanks for the update. In case there is anything else we can assist with or if you have any other issues, please let us know.

Best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi @asimag,
 
We will go ahead and close this ticket. If there is anything else that can be fixed or we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
