### ISSUE TITLE
Password Reset not working

### ISSUE THREAD

**Issue by raphcadiz** [creativetimofficial/ct-nuxt-argon-dashboard-pro-laravel#3]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [yes ] I am running the latest version
- [yes ] I checked the documentation and found no answer
- [ yes] I checked to make sure that this issue has not already been filed
- [yes ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Should send password reset notification

# Current Behavior
It's throwing error instead

# Failure Information (for bugs)
[2021-09-09 07:47:25] local.ERROR: Argument 1 passed to App\Http\Controllers\Api\V1\Auth\ForgotPasswordController::App\Http\Controllers\Api\V1\Auth\{closure}() must be an instance of Illuminate\Mail\Message, instance of App\Models\User given, called in C:\xampp\htdocs\ccaa-backend\vendor\laravel\framework\src\Illuminate\Auth\Passwords\PasswordBroker.php on line 66

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. follow forgot password link
2. submit reset password

**Comment by teamupdivision** [comment]
Hi @raphcadiz,

Thanks for reporting this issue and for using Creative Tim products.

We've pushed a fix to this problem.

You can access it by downloading the product from the downloads section on the Creative Tim website.
 
Please let us know if all works well now and there is anything else we can help with. 

All the best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi @raphcadiz,
 
Hope this solved the problem. We will go ahead and close this ticket. If there is anything else we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
